# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0001_initial'),
        ('cuestionario', '0002_auto_20210304_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='Encuesta',
            new_name='encuesta',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='muestra.Muestra'),
            preserve_default=False,
        ),
    ]
