# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-05 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0003_auto_20210304_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcion',
            name='texto',
        ),
        migrations.AddField(
            model_name='opcion',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
