# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0007_auto_20210305_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='contador',
            field=models.IntegerField(default=1),
        ),
    ]
