# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-05 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0008_respuesta_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcion', to='cuestionario.Opcion'),
        ),
    ]
