# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-05 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0011_auto_20210305_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='user',
            new_name='usuario',
        ),
    ]
