# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0001_initial'),
        ('cuestionario', '0012_auto_20210305_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='muestra.Muestra'),
            preserve_default=False,
        ),
    ]
