# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2021-03-05 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0014_auto_20210305_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='usuario',
            new_name='user',
        ),
    ]
